### ISSUE TITLE
Dual curation pipeline higher ploidies 

### ISSUE THREAD

**Issue by rsandean** [Nadolina/Rapid-curation-2.0#5]
Hi, 

I am currently assembling an autotetraploid and was looking into the dual curation pipeline to try and separate the 4 haplotypes. However I noticed that the scripts like AGP_correct.py are specifically made to recognise Hap1 and Hap2. Do I need to modify these to recognise Hap1, 2, 3, and 4? Or are there other ways of doing this? 

Thank you for any advice!

**Comment by Nadolina** [comment]
Hello, 

This pipeline was really only designed for diploid assemblies, because it was for my last lab space which worked nearly entirely on vertebrates. I think the AGP correct is not haplotype specific, but the wrapper curation_2.0_pipe.sh is. This was built rather quickly to address a gap in our workflow, and I had always intended to make it more flexible for polyploids but did not get around to it before leaving that group. I am really no longer on this project, so I encourage you to reach out to the Bioinformatics team at Rockefeller University to see if there are plans to implement this, or alternatively the DToL team at Wellcome Sanger, who may be better equipped to help you with polyploid work. 

Good luck!

**Comment by rsandean** [comment]
Ah ok! Thank you very much :)
